<?xml version='1.0' encoding='UTF-8'?>
<SmellBaseline>
  <ManuallySuppressedIssues/>
  <CurrentIssues>
    <ID>NewLineAtEndOfFile:build.gradle.kts$.build.gradle.kts</ID>
  </CurrentIssues>
</SmellBaseline>
